name: kimera_app
description: "kiMera configuration app. Developed by the Tokyo Denki University CPS Lab."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.4.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
